---
ansible_connection: local

repo_name: "{{ app_name }}"
openshift_url: https://{{ console_domain | default('console') }}.{{ base_openshift_url }}:443

build:
  NAME: "{{ app_name }}"
  S2I_BASE_IMAGE: python:3.6
  GIT_SOURCE_REF: master
  GIT_SOURCE_URI: git@bitbucket.org:{{ team_name }}/{{ repo_name }}.git
  GIT_SOURCE_SECRET: "{{ ci_cd.SECRET_NAME }}"
  PIPELINE_SOURCE_REPOSITORY_URL: git@bitbucket.org:{{ team_name }}/{{ repo_name }}.git
  PIPELINE_SOURCE_REPOSITORY_REF: master
  PIPELINE_SOURCE_SECRET: "{{ ci_cd.SECRET_NAME }}"

bitbucket_pipelines:
  - build_config: "{{ app_name }}-pipeline"
    namespace: "{{ ci_cd.NAMESPACE }}"

openshift_cluster_content:
- object: app-builds
  content:
  - name: "{{ app_name }}-build"
    template: "https://raw.githubusercontent.com/rht-labs/openshift-templates/master/s2i-app-build/template-with-secrets-and-pr.yml"
    params_from_vars: "{{ build }}"
    namespace: "{{ ci_cd.NAMESPACE }}"
    tags:
    - app-build
